INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'20000 Leagues Under the Sea', N'Verne, Jules', N'fiction', N'novel', 190, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Age of Discontuinity, The', N'Drucker, Peter', N'nonfiction', N'economics', 178, N'Random House')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Age of the Warrior, The', N'Fisk, Robert', N'nonfiction', N'history', 197, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Age of Wrath, The', N'Eraly, Abraham', N'nonfiction', N'history', 238, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Aghal Paghal', N'Deshpande, P L', N'nonfiction', N'misc', 212, N'Mauj')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Ahe Manohar Tari', N'Deshpande, Sunita', N'nonfiction', N'autobiography', 213, N'Mauj')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'All the President''s Men', N'Woodward, Bob', N'nonfiction', N'history', 177, N'Random House')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Amulet of Samarkand, The', N'Stroud, Jonathan', N'fiction', N'novel', 179, N'Random House')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Analysis, Vol I', N'Tao, Terence', N'tech', N'mathematics', 248, N'HBA')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Angels & Demons', N'Brown, Dan', N'fiction', N'novel', 178, N'Random House')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Animal Farm', N'Orwell, George', N'fiction', N'classic', 180, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Apulki', N'Deshpande, P L', N'nonfiction', N'misc', 211, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Argumentative Indian, The', N'Sen, Amartya', N'nonfiction', N'history', 209, N'Picador')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Arthashastra, The', N'Kautiyla', N'philosophy', N'philosophy', 214, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Artist and the Mathematician, The', N'Aczel, Amir', N'science', N'mathematics', 186, N'HighStakes')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Asami Asami', N'Deshpande, P L', N'fiction', N'novel', 205, N'Mauj')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Ashenden of The British Agent', N'Maugham, William S', N'fiction', N'classic', 160, N'Vintage')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Attorney, The', NULL, N'fiction', N'novel', 170, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Ayn Rand Answers', N'Rand, Ayn', N'philosophy', N'objectivism', 203, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Batatyachi Chal', N'Deshpande P L', N'fiction', N'novel', 200, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Batman Earth One', NULL, N'fiction', N'comic', 265, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Batman Handbook', NULL, N'fiction', N'comic', 270, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Batman: The Long Halloween', NULL, N'fiction', N'comic', 258, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Beautiful and the Damned, The', N'Deb, Siddhartha', N'nonfiction', N'history', 198, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Beyond Degrees', NULL, N'philosophy', N'education', 222, N'HarperCollins')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Beyond the Three Seas', N'Dalrymple, William', N'nonfiction', N'history', 197, N'Random House')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Birth of a Theorem', N'Villani, Cedric', N'science', N'mathematics', 234, N'Bodley Head')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Bookless in Baghdad', N'Tharoor, Shashi', N'nonfiction', N'history', 206, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Brethren, The', N'Grisham, John', N'fiction', N'novel', 174, N'Random House')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Broca''s Brain', N'Sagan, Carl', N'science', N'physics', 174, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Burning Bright', N'Steinbeck, John', N'fiction', N'classic', 175, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Case of the Lame Canary, The', N'Gardner, Earle Stanley', N'fiction', N'novel', 179, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Catch 22', N'Heller, Joseph', N'fiction', N'classic', 178, N'Random House')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Cathedral and the Bazaar, The', N'Raymond, Eric', N'tech', N'computer_science', 217, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Char Shabda', N'Deshpande, P L', N'nonfiction', N'misc', 214, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Christmas Carol, A', N'Dickens, Charles', N'fiction', N'classic', 196, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'City of Djinns', N'Dalrymple, William', N'nonfiction', N'history', 198, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'City of Joy, The', N'Lapierre, Dominique', N'fiction', N'novel', 177, N'vikas')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Clash of Civilizations and Remaking of the World Order', N'Huntington, Samuel', N'nonfiction', N'history', 228, N'Simon&Schuster')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Code Book, The', N'Singh, Simon', N'science', N'mathematics', 197, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Complete Mastermind, The', N'BBC', N'nonfiction', N'trivia', 178, N'BBC')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Complete Sherlock Holmes, The - Vol I', N'Doyle, Arthur Conan', N'fiction', N'classic', 176, N'Random House')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Complete Sherlock Holmes, The - Vol II', N'Doyle, Arthur Conan', N'fiction', N'classic', 176, N'Random House')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Computer Vision, A Modern Approach', N'Forsyth, David', N'tech', N'signal_processing', 255, N'Pearson')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Courtroom Genius, The', N'Sorabjee', N'nonfiction', N'autobiography', 217, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Crime and Punishment', N'Dostoevsky, Fyodor', N'fiction', N'classic', 180, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Crisis on Infinite Earths', NULL, N'fiction', N'comic', 258, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Data Analysis with Open Source Tools', N'Janert, Phillip', N'tech', N'data_science', 230, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Data Mining Handbook', N'Nisbet, Robert', N'tech', N'data_science', 242, N'Apress')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Data Scientists at Work', N'Sebastian Gutierrez', N'tech', N'data_science', 230, N'Apress')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Data Smart', N'Foreman, John', N'tech', N'data_science', 235, N'Wiley')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Data Structures Using C & C++', N'Tanenbaum, Andrew', N'tech', N'computer_science', 235, N'Prentice Hall')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Death of Superman, The', NULL, N'fiction', N'comic', 258, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Deceiver, The', N'Forsyth, Frederick', N'fiction', N'novel', 178, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Design with OpAmps', N'Franco, Sergio', N'tech', N'computer_science', 240, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Devil''s Advocate, The', N'West, Morris', N'fiction', N'novel', 178, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Discovery of India, The', N'Nehru, Jawaharlal', N'nonfiction', N'history', 230, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Doctor in the Nude', N'Gordon, Richard', N'fiction', N'novel', 179, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Doctor on the Brain', N'Gordon, Richard', N'fiction', N'novel', 204, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Dongri to Dubai', N'Zaidi, Hussain', N'nonfiction', N'history', 216, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Down and Out in Paris & London', N'Orwell, George', N'nonfiction', N'autobiography', 179, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Drunkard''s Walk, The', N'Mlodinow, Leonard', N'science', N'mathematics', 197, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Dylan on Dylan', N'Dylan, Bob', N'nonfiction', N'autobiography', 197, N'Random House')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Econometric Analysis', N'Greene, W. H.', N'tech', N'economics', 242, N'Pearson')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Electric Universe', N'Bodanis, David', N'science', N'physics', 201, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Elements of Information Theory', N'Thomas, Joy', N'tech', N'signal_processing', 229, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Empire of the Mughal - Brothers at War', N'Rutherford, Alex', N'nonfiction', N'history', 180, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Empire of the Mughal - Raiders from the North', N'Rutherford, Alex', N'nonfiction', N'history', 180, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Empire of the Mughal - Ruler of the World', N'Rutherford, Alex', N'nonfiction', N'history', 180, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Empire of the Mughal - The Serpent''s Tooth', N'Rutherford, Alex', N'nonfiction', N'history', 180, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Empire of the Mughal - The Tainted Throne', N'Rutherford, Alex', N'nonfiction', N'history', 180, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Eyeless in Gaza', N'Huxley, Aldous', N'fiction', N'novel', 180, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'False Impressions', N'Archer, Jeffery', N'fiction', N'novel', 177, N'Pan')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Farewell to Arms, A', N'Hemingway, Ernest', N'fiction', N'classic', 179, N'Rupa')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Final Crisis', NULL, N'fiction', N'comic', 257, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Flashpoint', NULL, N'fiction', N'comic', 265, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Freakonomics', N'Dubner, Stephen', N'science', N'economics', 197, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Free Will', N'Harris, Sam', N'nonfiction', N'psychology', 203, N'FreePress')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Freedom at Midnight', N'Lapierre, Dominique', N'nonfiction', N'history', 167, N'vikas')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'From Beirut to Jerusalem', N'Friedman, Thomas', N'nonfiction', N'history', 202, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Fundamentals of Wavelets', N'Goswami, Jaideva', N'tech', N'signal_processing', 228, N'Wiley')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Girl who kicked the Hornet''s Nest', N'Larsson, Steig', N'fiction', N'novel', 179, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Girl who played with Fire', N'Larsson, Steig', N'fiction', N'novel', 179, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Girl with the Dragon Tattoo', N'Larsson, Steig', N'fiction', N'novel', 179, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'God Created the Integers', N'Hawking, Stephen', N'tech', N'mathematics', 197, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Grapes of Wrath, The', N'Steinbeck, John', N'fiction', N'classic', 196, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Great Indian Novel, The', N'Tharoor, Shashi', N'fiction', N'novel', 198, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Great War for Civilization, The', N'Fisk, Robert', N'nonfiction', N'history', 197, N'HarperCollins')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Gun Gayin Awadi', N'Deshpande, P L', N'nonfiction', N'misc', 212, N'Mauj')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Hafasavnuk', N'Deshpande P L', N'fiction', N'novel', 211, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Half A Life', N'Naipaul, V S', N'fiction', N'novel', 196, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Hidden Connections, The', N'Capra, Fritjof', N'science', N'physics', 197, N'HarperCollins')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'History of England, Foundation', N'Ackroyd, Peter', N'nonfiction', N'history', 197, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'History of the DC Universe', NULL, N'fiction', N'comic', 258, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'History of Western Philosophy', N'Russell, Bertrand', N'philosophy', N'philosophy', 213, N'Routledge')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'How to Think Like Sherlock Holmes', N'Konnikova, Maria', N'nonfiction', N'psychology', 240, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Hunchback of Notre Dame, The', N'Hugo, Victor', N'fiction', N'classic', 175, N'Random House')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Idea of Justice, The', N'Sen, Amartya', N'philosophy', N'economics', 212, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Identity & Violence', N'Sen, Amartya', N'philosophy', N'philosophy', 219, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Idiot, The', N'Dostoevsky, Fyodor', N'fiction', N'classic', 197, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Image Processing & Mathematical Morphology', N'Shih, Frank', N'tech', N'signal_processing', 241, N'CRC')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Image Processing with MATLAB', N'Eddins, Steve', N'tech', N'signal_processing', 241, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'In a Free State', N'Naipaul, V. S.', N'fiction', N'novel', 196, N'Rupa')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'India from Midnight to Milennium', N'Tharoor, Shashi', N'nonfiction', N'history', 198, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'India''s Legal System', N'Nariman', N'nonfiction', N'legal', 177, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Information, The', N'Gleick, James', N'science', N'mathematics', 233, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Integration of the Indian States', N'Menon, V P', N'nonfiction', N'history', 217, N'Orient Blackswan')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Introduction to Algorithms', N'Cormen, Thomas', N'tech', N'computer_science', 234, N'MIT Press')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Jim Corbett Omnibus', N'Corbett, Jim', N'nonfiction', N'history', 223, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Journal of a Novel', N'Steinbeck, John', N'fiction', N'classic', 196, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Journal of Economics, vol 106 No 3', NULL, N'science', N'economics', 235, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Judge, The', NULL, N'fiction', N'novel', 170, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Jurassic Park', N'Crichton, Michael', N'fiction', N'novel', 174, N'Random House')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Justice League: The Villain''s Journey', NULL, N'fiction', N'comic', 258, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Justice League: Throne of Atlantis', NULL, N'fiction', N'comic', 258, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Justice, Judiciary and Democracy', N'Ranjan, Sudhanshu', N'nonfiction', N'legal', 224, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Karl Marx Biography', NULL, N'nonfiction', N'autobiography', 162, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Killing Joke, The', NULL, N'fiction', N'comic', 283, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Last Lecture, The', N'Pausch, Randy', N'nonfiction', N'autobiography', 197, N'Hyperion')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Last Mughal, The', N'Dalrymple, William', N'nonfiction', N'history', 199, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Learning OpenCV', N'Bradsky, Gary', N'tech', N'signal_processing', 232, N'O''Reilly')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Let Us C', N'Kanetkar, Yashwant', N'tech', N'computer_science', 213, N'Prentice Hall')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Life in Letters, A', N'Steinbeck, John', N'nonfiction', N'autobiography', 196, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Machine Learning for Hackers', N'Conway, Drew', N'tech', N'data_science', 233, N'O''Reilly')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Making Software', N'Oram, Andy', N'tech', N'computer_science', 232, N'O''Reilly')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Manasa', N'Kale, V P', N'nonfiction', N'misc', 213, N'Mauj')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Maqta-e-Ghalib', N'Garg, Sanjay', N'nonfiction', N'poetry', 221, N'Mauj')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Maugham''s Collected Short Stories, Vol 3', N'Maugham, William S', N'fiction', N'classic', 171, N'Vintage')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Mein Kampf', N'Hitler, Adolf', N'nonfiction', N'autobiography', 212, N'Rupa')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Men of Mathematics', N'Bell, E T', N'science', N'mathematics', 217, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Moon and Sixpence, The', N'Maugham, William S', N'fiction', N'classic', 180, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Moon is Down, The', N'Steinbeck, John', N'fiction', N'classic', 196, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'More Tears to Cry', N'Sassoon, Jean', N'fiction', N'novel', 235, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Mossad', N'Baz-Zohar, Michael', N'nonfiction', N'history', 236, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Murphy''s Law', NULL, N'philosophy', N'psychology', 178, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Nature of Statistical Learning Theory, The', N'Vapnik, Vladimir', N'tech', N'data_science', 230, N'Springer')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Neural Networks', N'Haykin, Simon', N'tech', N'data_science', 240, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'New Machiavelli, The', N'Wells, H. G.', N'fiction', N'novel', 180, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'New Markets & Other Essays', N'Drucker, Peter', N'science', N'economics', 176, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Numbers Behind Numb3rs, The', N'Devlin, Keith', N'science', N'mathematics', 202, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'O Jerusalem!', N'Lapierre, Dominique', N'nonfiction', N'history', 217, N'vikas')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'On Education', N'Russell, Bertrand', N'philosophy', N'education', 203, N'Routledge')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Once There Was a War', N'Steinbeck, John', N'nonfiction', N'history', 196, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'One', N'Bach, Richard', N'nonfiction', N'autobiography', 172, N'Dell')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Orientalism', N'Said, Edward', N'nonfiction', N'history', 197, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Outsider, The', N'Camus, Albert', N'fiction', N'classic', 198, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Oxford book of Modern Science Writing', N'Dawkins, Richard', N'science', N'science', 240, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Pattern Classification', N'Duda, Hart', N'tech', N'data_science', 241, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Phantom of Manhattan, The', N'Forsyth, Frederick', N'fiction', N'classic', 180, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Philosophy: Who Needs It', N'Rand, Ayn', N'philosophy', N'objectivism', 171, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Physics & Philosophy', N'Heisenberg, Werner', N'philosophy', N'science', 197, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Pillars of the Earth, The', N'Follett, Ken', N'fiction', N'novel', 176, N'Random House')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Pointers in C', N'Kanetkar, Yashwant', N'tech', N'computer_science', 213, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Political Philosophers', NULL, N'philosophy', N'politics', 162, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Power Electronics - Mohan', N'Mohan, Ned', N'tech', N'computer_science', 237, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Power Electronics - Rashid', N'Rashid, Muhammad', N'tech', N'computer_science', 235, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Prince, The', N'Machiavelli', N'fiction', N'classic', 173, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Principles of Communication Systems', N'Taub, Schilling', N'tech', N'signal_processing', 240, N'TMH')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Prisoner of Birth, A', N'Archer, Jeffery', N'fiction', N'novel', 176, N'Pan')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Python for Data Analysis', N'McKinney, Wes', N'tech', N'data_science', 233, N'O''Reilly')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Radiowaril Bhashane & Shrutika', N'Deshpande, P L', N'nonfiction', N'misc', 213, N'Mauj')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Raisin in the Sun, A', N'Hansberry, Lorraine', N'fiction', N'novel', 175, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Rationality & Freedom', N'Sen, Amartya', N'science', N'economics', 213, N'Springer')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Return of the Primitive', N'Rand, Ayn', N'philosophy', N'objectivism', 202, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Ropemaker, The', N'Dickinson, Peter', N'fiction', N'novel', 196, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Rosy is My Relative', N'Durrell, Gerald', N'fiction', N'novel', 176, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Russian Journal, A', N'Steinbeck, John', N'nonfiction', N'history', 196, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Scoop!', N'Nayar, Kuldip', N'nonfiction', N'history', 216, N'HarperCollins')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Sea of Poppies', N'Ghosh, Amitav', N'fiction', N'novel', 197, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Selected Short Stories', NULL, N'fiction', N'classic', 215, N'Jaico')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Short History of the World, A', N'Wells, H G', N'nonfiction', N'history', 197, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Signal and the Noise, The', N'Silver, Nate', N'tech', N'data_science', 233, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Simpsons & Their Mathematical Secrets', N'Singh, Simon', N'science', N'mathematics', 233, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Slaughterhouse Five', N'Vonnegut, Kurt', N'fiction', N'classic', 198, N'Random House')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Social Choice & Welfare, Vol 39 No. 1', N'Various', N'tech', N'economics', 235, N'Springer')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Soft Computing & Intelligent Systems', N'Gupta, Madan', N'tech', N'data_science', 242, N'Elsevier')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Statistical Decision Theory''', N'Pratt, John', N'tech', N'data_science', 236, N'MIT Press')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Statistical Learning Theory', N'Vapnik, Vladimir', N'tech', N'data_science', 228, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Story of Philosophy, The', N'Durant, Will', N'philosophy', N'history', 170, N'Pocket')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Structure & Interpretation of Computer Programs', N'Sussman, Gerald', N'tech', N'computer_science', 240, N'MIT Press')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Structure and Randomness', N'Tao, Terence', N'science', N'mathematics', 252, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Superfreakonomics', N'Dubner, Stephen', N'science', N'economics', 179, N'HarperCollins')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Superman Earth One - 1', NULL, N'fiction', N'comic', 259, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Superman Earth One - 2', NULL, N'fiction', N'comic', 258, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Surely You''re Joking Mr Feynman', N'Feynman, Richard', N'science', N'physics', 198, N'Random House')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Tales of Beedle the Bard', N'Rowling, J K', N'fiction', N'novel', 184, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Tales of Mystery and Imagination', N'Poe, Edgar Allen', N'fiction', N'classic', 172, N'HarperCollins')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Talking Straight', N'Iacoca, Lee', N'nonfiction', N'autobiography', 175, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Tao of Physics, The', N'Capra, Fritjof', N'science', N'physics', 179, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Textbook of Economic Theory', N'Stonier, Alfred', N'tech', N'economics', 242, N'Pearson')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Theory of Everything, The', N'Hawking, Stephen', N'science', N'physics', 217, N'Jaico')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Think Complexity', N'Downey, Allen', N'tech', N'data_science', 230, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'To Sir With Love', N'Braithwaite', N'fiction', N'classic', 197, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Trembling of a Leaf, The', N'Maugham, William S', N'fiction', N'novel', 205, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Trial, The', N'Kafka, Frank', N'fiction', N'classic', 198, N'Random House')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Uncommon Wisdom', N'Capra, Fritjof', N'nonfiction', N'anthology', 197, N'Fontana')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Unpopular Essays', N'Russell, Bertrand', N'philosophy', N'philosophy', 198, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Urlasurla', N'Deshpande P L', N'fiction', N'novel', 211, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Veil: Secret Wars of the CIA', N'Woodward, Bob', N'nonfiction', N'history', 171, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Veteran, The', N'Forsyth, Frederick', N'fiction', N'novel', 177, N'Transworld')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Vyakti ani Valli', N'Deshpande, P L', N'nonfiction', N'misc', 211, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'We the Living', N'Rand, Ayn', N'fiction', N'novel', 178, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'We the Nation', N'Palkhivala', N'philosophy', N'philosophy', 216, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'We the People', N'Palkhivala', N'philosophy', N'philosophy', 216, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Wealth of Nations, The', N'Smith, Adam', N'science', N'economics', 175, N'Random House')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Winter of Our Discontent, The', N'Steinbeck, John', N'fiction', N'classic', 196, N'Penguin')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'World''s Great Thinkers, The', NULL, N'science', N'physics', 189, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'World''s Greatest Short Stories, The', NULL, N'fiction', N'classic', 217, N'Jaico')
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'World''s Greatest Trials, The', NULL, N'nonfiction', N'history', 210, NULL)
INSERT INTO [dbo].[bookdata] ([Title], [Author], [Genre], [SubGenre], [Height], [Publisher]) VALUES (N'Zen & The Art of Motorcycle Maintenance', N'Pirsig, Robert', N'philosophy', N'autobiography', 172, N'Vintage')
